PATCH http://php-pro.loc/api/v1/books/101
Content-Type: application/json
Accept: application/json

{
    "name": "test778",
    "year": 1991,
    "lang": "en",
    "pages": 555,
    "categoryId": 2
}
